version: "3.3"

services:
  chrome:
    image: selenium/standalone-chrome
    container_name: calendar-standalone-chrome
  mongodb:
    image: mongo:latest
    container_name: calendar-record-mongodb
    environment:
      MONGO_INITDB_DATABASE: Record
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./mongo-volumn:/data/db
  express:
    image: ntou-calendar-fetcher-image
    container_name: ntou-calendar-fetcher
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    links:
      - "mongodb:mongodb"
      - "chrome:chrome"
